env: "local"
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "23022005Ru"
  dbname: "mapped"
  sslmode: "disable"
user_service:
  port: ":8081"
place_service:
  port: ":8082"
recommendation_service:
  port: ":8083"

kafka:
  first_broker_port: "9093"

jwt:
  secret: "afsdhfkds3yr274rtb743t34t2tr8t3"